- hosts: all
  become: yes
  become_method: sudo
  vars:
    base_image: centos:7
  tasks:
    - name: Add Docker
      yum: name=docker state=present

    - name: Add python-docker-py
      yum: name=python-docker-py state=present

    - name: Docker service must be started
      service: name=docker state=started

    - name: Pull Docker Centos base image
      docker: pull=missing image={{ base_image }}
      notify: Check centos is present

  handlers:
    - name: Check centos base image is present
      docker: image={{ base_image }} state=present
