#!/bin/bash

if [ $1 = "-i" ] ; then
  echo "Using interactive mode"

  echo -e "Write the name of the remote user: \c"
  read user

  echo -e "Write the host Ip or name: \c"
  read host

  echo "A public key from ~/.ssh/id_rsa.pub will be used"
  echo "Remote machine will probably ask for permissions password"

  ssh-copy-id -i ~/.ssh/id_rsa.pub $user@$host
else
  echo "Use ssh-copy-id command. example:"
  echo "ssh-copy-id -i ~/.ssh/id_rsa.pub user@host"
fi
