- name: Add Docker
  yum: name=docker state=present

- name: Add python-docker-py
  yum: name=python-docker-py state=present

- name: Docker service must be started
  service: name=docker state=started
