- hosts: all
  become: yes
  become_method: sudo
  vars:
    # For handlers/restart-docker.yml
    http_port: 3000
    host_port: 41600

    # Shared here and in handlers/restart-docker.yml
    image_name: sayden/node-server

    # Dockerfile to use and destination in target's machine
    source_dockerfile_dir: /home/mariocaster/tmp/docker-cookbook/centos-node/Dockerfile
    docker_dest_dir: /srv/docker

    git_repo: https://github.com/sayden/simplest-express-server.git
  tasks:
    - include: tasks/copy-dockerfile.yml

    - name: Re/build Docker image
      docker_image: name={{ image_name }}
                    path={{ docker_dest_dir }}
                    nocache=yes
                    state=build
      notify: Restart Docker image

  handlers:
    - include: handlers/restart-docker.yml
