- hosts: all
  become: yes
  become_method: sudo
  vars:
    # For handlers/restart-docker.yml
    http_port: 3000
    host_port: 41600

    # Shared here and in handlers/restart-docker.yml
    image_name: sayden/node-server
    
    git_repo: https://github.com/sayden/simplest-express-server.git
    docker_dest_dir: /srv/docker
  tasks:

    - name: Re/build Docker image
      docker_image: name={{ image_name }}
                    path={{ docker_dest_dir }}
                    nocache=yes
                    state=build
      notify: Restart Docker image

  handlers:
    - include: handlers/restart-docker.yml
